name: Examples

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-windows:
    runs-on: windows-latest

    strategy:
      matrix:
        build_type: [Debug, Release]
        production_mode: [ON, OFF]

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake . -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DB_PRODUCTION_MODE=${{matrix.production_mode}}

    - name: Build and run all examples
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}} --target run_all_examples

  build-linux:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        cxx_compiler: [g++, clang++]
        build_type: [Debug, Release]
        production_mode: [ON, OFF]

    steps:
      - uses: actions/checkout@v3

      - name: Configure CMake
        run: cmake . -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DB_PRODUCTION_MODE=${{matrix.production_mode}} -DCMAKE_CXX_COMPILER=${{matrix.cxx_compiler}}

      - name: Build and run all examples
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}} --target run_all_examples

  build-mac:
    runs-on: macos-latest

    strategy:
      matrix:
        cxx_compiler: [g++, clang++]
        build_type: [Debug, Release]
        production_mode: [ON, OFF]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Xcode and AppleClang
        uses: actions/setup-xcode@v2
        with:
          xcode-version: '13.2'  # Use the version of Xcode you prefer

      - name: Configure CMake
        run: cmake . -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DB_PRODUCTION_MODE=${{matrix.production_mode}} -DCMAKE_CXX_COMPILER=${{matrix.cxx_compiler}}

      - name: Build and run all examples
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}} --target run_all_examples
